# OpenWrt-CI workflow
# 参考 P3TERX/Actions-OpenWrt 脚本及讨论改进措施
name: OpenWrt-CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_openwrt:
    name: Build OpenWrt Firmware
    runs-on: ubuntu-22.04

    steps:
      - name: Clean up disk space and set TMPDIR
        run: |
          echo "Cleaning /tmp directory..."
          sudo rm -rf /tmp/* || true
          # 在 $HOME 下创建一个临时目录以确保空间充足
          mkdir -p $HOME/tmp
          export TMPDIR=$HOME/tmp
          echo "TMPDIR set to: $TMPDIR"
          echo "Disk usage after cleanup:"
          df -h

      - name: Free up additional disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout OpenWrt source
        uses: actions/checkout@v4

      - name: Update feeds
        run: |
          # 检查 feeds.conf.default 是否存在，如果不存在则判断 feeds.conf.default.sample 是否存在
          if [ ! -f feeds.conf.default ]; then
            if [ -f feeds.conf.default.sample ]; then
              echo "feeds.conf.default not found, copying from feeds.conf.default.sample"
              cp feeds.conf.default.sample feeds.conf.default
            else
              echo "No feeds configuration file found, creating an empty feeds.conf.default"
              touch feeds.conf.default
            fi
          fi
          # 修改 feeds.conf.default 中的设置
          sed -i 's/#src-git helloworld/src-git helloworld/g' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate default config
        run: make defconfig

      - name: Download packages
        run: make download -j16

      - name: Compile firmware
        env:
          TMPDIR: ${{ runner.workspace }}/tmp  # 指定编译过程中使用的临时目录
        run: |
          mkdir -p $TMPDIR
          echo "Using TMPDIR: $TMPDIR"
          # 尝试并行编译，失败则切换到单线程详细模式
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Disk usage after compile:"
          df -h
          echo "Directory sizes (excluding build_dir and bin):"
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          echo "build_dir size:"
          du -h --max-depth=1 ./build_dir
          echo "bin size:"
          du -h --max-depth=1 ./bin

      - name: Prepare artifacts
        run: |
          mkdir -p ./artifact/package ./artifact/buildinfo
          # 删除生成过程中多余的 packages 文件夹
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f \( -name "*.buildinfo" -o -name "*.manifest" \)) ./artifact/buildinfo/

      - name: Upload buildinfo artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
